# Site
name: 'Logit Blog'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: 'logitblog'
google_analytics: 'UA-37914193-1'
email: 'mail@logitblog.com'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  
authors:
    ryan:
      name:           Ryan Ververs-Bijkerk
      picture:        /assets/images/authors/ryan.png
      bio:            "Ryan is currently a Technical Evangelist at RawWorks focused on the End-User Computing area. Ryan is primarily focusing on the user experience in centralized desktop environments."
      twitter:        https://twitter.com/logitblog
      linkedin:       https://www.linkedin.com/in/ryanbijkerk/
      github:         https://github.com/RyanBijkerk
      reddit:         https://www.reddit.com/user/ryanbijkerk
    ivan:
      name:           Ivan Maatman
      picture:        /assets/images/authors/ivan.png
      bio:            "Ivan is a experienced Consultant with a demonstrated history of working in the information technology and services industry. Skilled in Microsoft ConfigMgr, Desktop Deplyoment, App-V, Windows Server and Virtualization."
      linkedin:       https://www.linkedin.com/in/ivanmaatman/
    niels:
      name:           Niels Geursen
      picture:        /assets/images/authors/niels.png
      bio:            "Niels started his career in the year 2000. In the past 17 years, he learned about the IT challenges from small to enterprise companies. In all these years Niels also got the opportunity to educate himself by following courses and doing exams for Citrix, Microsoft, and VMware."
      linkedin:       https://www.linkedin.com/in/nielsgeursen/
      twitter:        https://twitter.com/NielsGeursen
    matthijs:
      name:           Matthijs de Booij
      picture:        /assets/images/authors/matthijs.png
      bio:            "Matthijs his mission: inspiring others to discover new ways of working. Over the years, Matthijs have provided 100+ training courses and workshops in the fields of Scrum, Agile Product Development, Kanban, and personal leadership."
      linkedin:       https://www.linkedin.com/in/matthijsdebooij/
      twitter:        https://twitter.com/agileteamswork
    marc:
      name:           Marc Jacobs
      picture:        /assets/images/authors/marc.png
      bio:            "Marc is Innovative Software Developer and Co-founder at Jump. Jump helps businesses JUMP to the next level by building awesome apps that scale."
      linkedin:       https://www.linkedin.com/in/scrumdeveloper/
      twitter:        https://twitter.com/jacobsmv
    dennis:
      name:           Dennis Geerling
      picture:        /assets/images/authors/dennis.png
      bio:            "Dennis is a troubleshoot guru and has over 10 years of EUC experience. Dennis is a proud Dutch man, but currently living the American dream in sunny California."
      linkedin:       https://www.linkedin.com/in/dennis-geerlings-13411933/
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]